### ISSUE TITLE
Failing to automatically detect client ip if none provided

### ISSUE THREAD

**Issue by mofman** [stevebauman/location#47]
Using Laravel 5.6 & PHP 7.2

```
$ip = isset($_SERVER['HTTP_CLIENT_IP'])?$_SERVER['HTTP_CLIENT_IP']:isset($_SERVER['HTTP_X_FORWARDED_FOR'])?$_SERVER['HTTP_X_FORWARDED_FOR']:$_SERVER['REMOTE_ADDR'];  
$location = new Location;

// fails -  ErrorException (E_NOTICE) Trying to get property 'countryName' of non-object
$this->country = $location->get()->countryName;

// works
$this->country = $location->get($ip)->countryName;

```

**Comment by mofman** [comment]
to be clear this dd(Location::get()); returns false

**Comment by SiroDiaz** [comment]
Same error when i update to 3.0. Returns false Location::get().

**Comment by JLanky** [comment]
> to be clear dd(Location::get()); returns false

I got an error when I used Homstead. Server ip strange in this case is not determined

**Comment by jackbayliss** [comment]
If you're getting this error, it may be because you're blacklisted from FreeGeoIp, IpInfo is the default driver by default, and unless you've registered it won't work properly (as you need an account) causing it to fallback to FreeGeoIp. My suggestion is try the [Maxmind] solution (https://github.com/stevebauman/location#setting-up-maxmind) for now. @mofman, @SiroDiaz , @JLanky

**Comment by stevebauman** [comment]
Apologies for the dreadfully late reply on this issue. Thanks @jackbayliss for answering this one 👍 

Using the Maxmind driver as @jackbayliss will certainly work -- and is the preferred method, since you won't encounter any throttling issues as you would with any of the free web services. It simply requires some further setup (such as registering for a MaxMind account, and downloading the `.mmdb` file).

If anyone is still encountering issues then comment back and I will re-open this 👍
