### ISSUE TITLE
I m getting Localhost IP Address and Null Location Value.

### ISSUE THREAD

**Issue by vaibhavisojitra25** [stevebauman/location#59]
Hello
I have install location package but getting null response with localhost IP.
`192.168.22.29`
```
Stevebauman\Location\Position Object
(
    [countryName] => 
    [countryCode] => 
    [regionCode] => 
    [regionName] => 
    [cityName] => 
    [zipCode] => 
    [isoCode] => 
    [postalCode] => 
    [latitude] => 
    [longitude] => 
    [metroCode] => 
    [areaCode] => 
    [driver] => Stevebauman\Location\Drivers\IpInfo
)
```
Can anyone please give me a solution about how can i get lat long of current user??

**Comment by jackbayliss** [comment]
Try changing your driver, I think the [code](https://github.com/stevebauman/location/blob/af1bf6e6a1d0fdca746963d97dbc7ae5f4998240/src/Drivers/IpInfo.php#L49) no longer works as they've updated their website. It needs to be changed (I think), I will create a pull with the fix if I get time. 

For now, try changing the driver to IpApi, or an alternative [here](https://github.com/stevebauman/location/blob/master/src/Config/config.php#L14)

**Comment by stevebauman** [comment]
Hi @vaibhavisojitra25,

> I have install location package but getting null response with localhost IP.

This will get you a `null` response because no services can locate you with a `localhost` IP address.

You must enable localhost `testing` to `true` and set an IP address manually:

https://github.com/stevebauman/location/blob/1924c291264cda5eddf7395aa53b8a280679ffac/src/Config/config.php#L105-L111
